//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSolution.HomeRepairVR.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityMaterial
    {
        public int ActivityMaterialId { get; set; }
        public int ActivityId { get; set; }
        public int MaterialId { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Material Material { get; set; }
    }
}
