//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSolution.HomeRepairVR.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticsDetail
    {
        public int StatisticDetailId { get; set; }
        public int StatisticsId { get; set; }
        public Nullable<int> StepId { get; set; }
        public string Status { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string Description { get; set; }
        public int StatisticTimeElapsed { get; set; }
        public Nullable<int> StepsCorrects { get; set; }
        public Nullable<int> StepsIncorrects { get; set; }
        public string StatusActivity { get; set; }
    
        public virtual Statistics Statistics { get; set; }
        public virtual Step Step { get; set; }
    }
}
