//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSolution.HomeRepairVR.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Statistics()
        {
            this.StatisticsDetail = new HashSet<StatisticsDetail>();
        }
    
        public int StatisticsId { get; set; }
        public int UserActivityId { get; set; }
        public System.TimeSpan StatisticTimeElapsed { get; set; }
        public System.DateTime DateCreate { get; set; }
        public System.DateTime DateUpdate { get; set; }
    
        public virtual UserActivity UserActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatisticsDetail> StatisticsDetail { get; set; }
    }
}
